spring:
  application:
    name: Journal App

  datasource:
    url: jdbc:mysql://localhost:3306/journal_db
    username: root
    password: 9274@Indian
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  main:
    allow-circular-references: true

  profiles:
    active: dev